/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as OnboardingWaiting_listRouteImport } from './routes/onboarding/waiting_list'
import { Route as OnboardingRegisterRouteImport } from './routes/onboarding/register'
import { Route as LoginValidateotpRouteImport } from './routes/login/validateotp'
import { Route as LoginForgotPasswordRouteImport } from './routes/login/forgot-password'
import { Route as LoginCallbackRouteImport } from './routes/login/callback'
import { Route as AppUserIndexRouteImport } from './routes/_app/user/index'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app/transactions/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppConnectionsIndexRouteImport } from './routes/_app/connections/index'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app/categories/index'
import { Route as AppBudgetsIndexRouteImport } from './routes/_app/budgets/index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppUserEditRouteImport } from './routes/_app/user/edit'
import { Route as AppTransactionsOldIndexRouteImport } from './routes/_app/transactions/oldIndex'
import { Route as AppTransactionsInboxRouteImport } from './routes/_app/transactions/inbox'
import { Route as AppTransactionsCreateRouteImport } from './routes/_app/transactions/create'
import { Route as AppReportsCashflowRouteImport } from './routes/_app/reports/cashflow'
import { Route as AppConnectionsIdRouteImport } from './routes/_app/connections/$id'
import { Route as AppCategoriesOldRouteImport } from './routes/_app/categories/old'
import { Route as AppCategoriesNewRouteImport } from './routes/_app/categories/new'
import { Route as AppCategoriesIdRouteImport } from './routes/_app/categories/$id'
import { Route as AppBudgetsCreateRouteImport } from './routes/_app/budgets/create'
import { Route as AppBudgetsIdRouteImport } from './routes/_app/budgets/$id'
import { Route as AppAccountsNewRouteImport } from './routes/_app/accounts/new'
import { Route as AppAccountsIdRouteImport } from './routes/_app/accounts/$id'
import { Route as AppSettingsInstitutionsIndexRouteImport } from './routes/_app/settings/institutions/index'
import { Route as AppConnectionsConnectIndexRouteImport } from './routes/_app/connections/connect/index'
import { Route as AppCategoriesRulesIndexRouteImport } from './routes/_app/categories/rules/index'
import { Route as AppConnectionsConnectCallbackRouteImport } from './routes/_app/connections/connect/callback'
import { Route as AppCategoriesRulesCreateRouteImport } from './routes/_app/categories/rules/create'
import { Route as AppCategoriesIdEditRouteImport } from './routes/_app/categories/$id_.edit'
import { Route as AppAccountsIdEditRouteImport } from './routes/_app/accounts/$id_.edit'

const UserdeletedLazyRouteImport = createFileRoute('/userdeleted')()
const IndexLazyRouteImport = createFileRoute('/')()
const AppToolsMortgageLazyRouteImport = createFileRoute(
  '/_app/tools/mortgage',
)()
const AppToolsLoanLazyRouteImport = createFileRoute('/_app/tools/loan')()

const UserdeletedLazyRoute = UserdeletedLazyRouteImport.update({
  id: '/userdeleted',
  path: '/userdeleted',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/userdeleted.lazy').then((d) => d.Route))
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWaiting_listRoute = OnboardingWaiting_listRouteImport.update({
  id: '/onboarding/waiting_list',
  path: '/onboarding/waiting_list',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRegisterRoute = OnboardingRegisterRouteImport.update({
  id: '/onboarding/register',
  path: '/onboarding/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginValidateotpRoute = LoginValidateotpRouteImport.update({
  id: '/login/validateotp',
  path: '/login/validateotp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginForgotPasswordRoute = LoginForgotPasswordRouteImport.update({
  id: '/login/forgot-password',
  path: '/login/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsIndexRoute = AppConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsIndexRoute = AppBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsMortgageLazyRoute = AppToolsMortgageLazyRouteImport.update({
  id: '/tools/mortgage',
  path: '/tools/mortgage',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/tools/mortgage.lazy').then((d) => d.Route),
)
const AppToolsLoanLazyRoute = AppToolsLoanLazyRouteImport.update({
  id: '/tools/loan',
  path: '/tools/loan',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/tools/loan.lazy').then((d) => d.Route),
)
const AppUserEditRoute = AppUserEditRouteImport.update({
  id: '/user/edit',
  path: '/user/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsOldIndexRoute = AppTransactionsOldIndexRouteImport.update({
  id: '/transactions/oldIndex',
  path: '/transactions/oldIndex',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsInboxRoute = AppTransactionsInboxRouteImport.update({
  id: '/transactions/inbox',
  path: '/transactions/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsCreateRoute = AppTransactionsCreateRouteImport.update({
  id: '/transactions/create',
  path: '/transactions/create',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCashflowRoute = AppReportsCashflowRouteImport.update({
  id: '/reports/cashflow',
  path: '/reports/cashflow',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsIdRoute = AppConnectionsIdRouteImport.update({
  id: '/connections/$id',
  path: '/connections/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesOldRoute = AppCategoriesOldRouteImport.update({
  id: '/categories/old',
  path: '/categories/old',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesNewRoute = AppCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIdRoute = AppCategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsCreateRoute = AppBudgetsCreateRouteImport.update({
  id: '/budgets/create',
  path: '/budgets/create',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsIdRoute = AppBudgetsIdRouteImport.update({
  id: '/budgets/$id',
  path: '/budgets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsNewRoute = AppAccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsInstitutionsIndexRoute =
  AppSettingsInstitutionsIndexRouteImport.update({
    id: '/settings/institutions/',
    path: '/settings/institutions/',
    getParentRoute: () => AppRoute,
  } as any)
const AppConnectionsConnectIndexRoute =
  AppConnectionsConnectIndexRouteImport.update({
    id: '/connections/connect/',
    path: '/connections/connect/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCategoriesRulesIndexRoute = AppCategoriesRulesIndexRouteImport.update({
  id: '/categories/rules/',
  path: '/categories/rules/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsConnectCallbackRoute =
  AppConnectionsConnectCallbackRouteImport.update({
    id: '/connections/connect/callback',
    path: '/connections/connect/callback',
    getParentRoute: () => AppRoute,
  } as any)
const AppCategoriesRulesCreateRoute =
  AppCategoriesRulesCreateRouteImport.update({
    id: '/categories/rules/create',
    path: '/categories/rules/create',
    getParentRoute: () => AppRoute,
  } as any)
const AppCategoriesIdEditRoute = AppCategoriesIdEditRouteImport.update({
  id: '/categories/$id_/edit',
  path: '/categories/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIdEditRoute = AppAccountsIdEditRouteImport.update({
  id: '/accounts/$id_/edit',
  path: '/accounts/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/userdeleted': typeof UserdeletedLazyRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/login/validateotp': typeof LoginValidateotpRoute
  '/onboarding/register': typeof OnboardingRegisterRoute
  '/onboarding/waiting_list': typeof OnboardingWaiting_listRoute
  '/login': typeof LoginIndexRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/accounts/new': typeof AppAccountsNewRoute
  '/budgets/$id': typeof AppBudgetsIdRoute
  '/budgets/create': typeof AppBudgetsCreateRoute
  '/categories/$id': typeof AppCategoriesIdRoute
  '/categories/new': typeof AppCategoriesNewRoute
  '/categories/old': typeof AppCategoriesOldRoute
  '/connections/$id': typeof AppConnectionsIdRoute
  '/reports/cashflow': typeof AppReportsCashflowRoute
  '/transactions/create': typeof AppTransactionsCreateRoute
  '/transactions/inbox': typeof AppTransactionsInboxRoute
  '/transactions/oldIndex': typeof AppTransactionsOldIndexRoute
  '/user/edit': typeof AppUserEditRoute
  '/tools/loan': typeof AppToolsLoanLazyRoute
  '/tools/mortgage': typeof AppToolsMortgageLazyRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/budgets': typeof AppBudgetsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/connections': typeof AppConnectionsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/user': typeof AppUserIndexRoute
  '/accounts/$id/edit': typeof AppAccountsIdEditRoute
  '/categories/$id/edit': typeof AppCategoriesIdEditRoute
  '/categories/rules/create': typeof AppCategoriesRulesCreateRoute
  '/connections/connect/callback': typeof AppConnectionsConnectCallbackRoute
  '/categories/rules': typeof AppCategoriesRulesIndexRoute
  '/connections/connect': typeof AppConnectionsConnectIndexRoute
  '/settings/institutions': typeof AppSettingsInstitutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/userdeleted': typeof UserdeletedLazyRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/login/validateotp': typeof LoginValidateotpRoute
  '/onboarding/register': typeof OnboardingRegisterRoute
  '/onboarding/waiting_list': typeof OnboardingWaiting_listRoute
  '/login': typeof LoginIndexRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/accounts/new': typeof AppAccountsNewRoute
  '/budgets/$id': typeof AppBudgetsIdRoute
  '/budgets/create': typeof AppBudgetsCreateRoute
  '/categories/$id': typeof AppCategoriesIdRoute
  '/categories/new': typeof AppCategoriesNewRoute
  '/categories/old': typeof AppCategoriesOldRoute
  '/connections/$id': typeof AppConnectionsIdRoute
  '/reports/cashflow': typeof AppReportsCashflowRoute
  '/transactions/create': typeof AppTransactionsCreateRoute
  '/transactions/inbox': typeof AppTransactionsInboxRoute
  '/transactions/oldIndex': typeof AppTransactionsOldIndexRoute
  '/user/edit': typeof AppUserEditRoute
  '/tools/loan': typeof AppToolsLoanLazyRoute
  '/tools/mortgage': typeof AppToolsMortgageLazyRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/budgets': typeof AppBudgetsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/connections': typeof AppConnectionsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/user': typeof AppUserIndexRoute
  '/accounts/$id/edit': typeof AppAccountsIdEditRoute
  '/categories/$id/edit': typeof AppCategoriesIdEditRoute
  '/categories/rules/create': typeof AppCategoriesRulesCreateRoute
  '/connections/connect/callback': typeof AppConnectionsConnectCallbackRoute
  '/categories/rules': typeof AppCategoriesRulesIndexRoute
  '/connections/connect': typeof AppConnectionsConnectIndexRoute
  '/settings/institutions': typeof AppSettingsInstitutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/_app': typeof AppRouteWithChildren
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/userdeleted': typeof UserdeletedLazyRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/login/validateotp': typeof LoginValidateotpRoute
  '/onboarding/register': typeof OnboardingRegisterRoute
  '/onboarding/waiting_list': typeof OnboardingWaiting_listRoute
  '/login/': typeof LoginIndexRoute
  '/_app/accounts/$id': typeof AppAccountsIdRoute
  '/_app/accounts/new': typeof AppAccountsNewRoute
  '/_app/budgets/$id': typeof AppBudgetsIdRoute
  '/_app/budgets/create': typeof AppBudgetsCreateRoute
  '/_app/categories/$id': typeof AppCategoriesIdRoute
  '/_app/categories/new': typeof AppCategoriesNewRoute
  '/_app/categories/old': typeof AppCategoriesOldRoute
  '/_app/connections/$id': typeof AppConnectionsIdRoute
  '/_app/reports/cashflow': typeof AppReportsCashflowRoute
  '/_app/transactions/create': typeof AppTransactionsCreateRoute
  '/_app/transactions/inbox': typeof AppTransactionsInboxRoute
  '/_app/transactions/oldIndex': typeof AppTransactionsOldIndexRoute
  '/_app/user/edit': typeof AppUserEditRoute
  '/_app/tools/loan': typeof AppToolsLoanLazyRoute
  '/_app/tools/mortgage': typeof AppToolsMortgageLazyRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/budgets/': typeof AppBudgetsIndexRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/connections/': typeof AppConnectionsIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_app/user/': typeof AppUserIndexRoute
  '/_app/accounts/$id_/edit': typeof AppAccountsIdEditRoute
  '/_app/categories/$id_/edit': typeof AppCategoriesIdEditRoute
  '/_app/categories/rules/create': typeof AppCategoriesRulesCreateRoute
  '/_app/connections/connect/callback': typeof AppConnectionsConnectCallbackRoute
  '/_app/categories/rules/': typeof AppCategoriesRulesIndexRoute
  '/_app/connections/connect/': typeof AppConnectionsConnectIndexRoute
  '/_app/settings/institutions/': typeof AppSettingsInstitutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/register'
    | '/userdeleted'
    | '/login/callback'
    | '/login/forgot-password'
    | '/login/validateotp'
    | '/onboarding/register'
    | '/onboarding/waiting_list'
    | '/login'
    | '/accounts/$id'
    | '/accounts/new'
    | '/budgets/$id'
    | '/budgets/create'
    | '/categories/$id'
    | '/categories/new'
    | '/categories/old'
    | '/connections/$id'
    | '/reports/cashflow'
    | '/transactions/create'
    | '/transactions/inbox'
    | '/transactions/oldIndex'
    | '/user/edit'
    | '/tools/loan'
    | '/tools/mortgage'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/connections'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/user'
    | '/accounts/$id/edit'
    | '/categories/$id/edit'
    | '/categories/rules/create'
    | '/connections/connect/callback'
    | '/categories/rules'
    | '/connections/connect'
    | '/settings/institutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/register'
    | '/userdeleted'
    | '/login/callback'
    | '/login/forgot-password'
    | '/login/validateotp'
    | '/onboarding/register'
    | '/onboarding/waiting_list'
    | '/login'
    | '/accounts/$id'
    | '/accounts/new'
    | '/budgets/$id'
    | '/budgets/create'
    | '/categories/$id'
    | '/categories/new'
    | '/categories/old'
    | '/connections/$id'
    | '/reports/cashflow'
    | '/transactions/create'
    | '/transactions/inbox'
    | '/transactions/oldIndex'
    | '/user/edit'
    | '/tools/loan'
    | '/tools/mortgage'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/connections'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/user'
    | '/accounts/$id/edit'
    | '/categories/$id/edit'
    | '/categories/rules/create'
    | '/connections/connect/callback'
    | '/categories/rules'
    | '/connections/connect'
    | '/settings/institutions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/logout'
    | '/register'
    | '/userdeleted'
    | '/login/callback'
    | '/login/forgot-password'
    | '/login/validateotp'
    | '/onboarding/register'
    | '/onboarding/waiting_list'
    | '/login/'
    | '/_app/accounts/$id'
    | '/_app/accounts/new'
    | '/_app/budgets/$id'
    | '/_app/budgets/create'
    | '/_app/categories/$id'
    | '/_app/categories/new'
    | '/_app/categories/old'
    | '/_app/connections/$id'
    | '/_app/reports/cashflow'
    | '/_app/transactions/create'
    | '/_app/transactions/inbox'
    | '/_app/transactions/oldIndex'
    | '/_app/user/edit'
    | '/_app/tools/loan'
    | '/_app/tools/mortgage'
    | '/_app/accounts/'
    | '/_app/budgets/'
    | '/_app/categories/'
    | '/_app/connections/'
    | '/_app/dashboard/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/transactions/'
    | '/_app/user/'
    | '/_app/accounts/$id_/edit'
    | '/_app/categories/$id_/edit'
    | '/_app/categories/rules/create'
    | '/_app/connections/connect/callback'
    | '/_app/categories/rules/'
    | '/_app/connections/connect/'
    | '/_app/settings/institutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AppRoute: typeof AppRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  UserdeletedLazyRoute: typeof UserdeletedLazyRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginForgotPasswordRoute: typeof LoginForgotPasswordRoute
  LoginValidateotpRoute: typeof LoginValidateotpRoute
  OnboardingRegisterRoute: typeof OnboardingRegisterRoute
  OnboardingWaiting_listRoute: typeof OnboardingWaiting_listRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userdeleted': {
      id: '/userdeleted'
      path: '/userdeleted'
      fullPath: '/userdeleted'
      preLoaderRoute: typeof UserdeletedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/waiting_list': {
      id: '/onboarding/waiting_list'
      path: '/onboarding/waiting_list'
      fullPath: '/onboarding/waiting_list'
      preLoaderRoute: typeof OnboardingWaiting_listRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/register': {
      id: '/onboarding/register'
      path: '/onboarding/register'
      fullPath: '/onboarding/register'
      preLoaderRoute: typeof OnboardingRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/validateotp': {
      id: '/login/validateotp'
      path: '/login/validateotp'
      fullPath: '/login/validateotp'
      preLoaderRoute: typeof LoginValidateotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/forgot-password': {
      id: '/login/forgot-password'
      path: '/login/forgot-password'
      fullPath: '/login/forgot-password'
      preLoaderRoute: typeof LoginForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/user/': {
      id: '/_app/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/': {
      id: '/_app/connections/'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/': {
      id: '/_app/budgets/'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/mortgage': {
      id: '/_app/tools/mortgage'
      path: '/tools/mortgage'
      fullPath: '/tools/mortgage'
      preLoaderRoute: typeof AppToolsMortgageLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/loan': {
      id: '/_app/tools/loan'
      path: '/tools/loan'
      fullPath: '/tools/loan'
      preLoaderRoute: typeof AppToolsLoanLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user/edit': {
      id: '/_app/user/edit'
      path: '/user/edit'
      fullPath: '/user/edit'
      preLoaderRoute: typeof AppUserEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/oldIndex': {
      id: '/_app/transactions/oldIndex'
      path: '/transactions/oldIndex'
      fullPath: '/transactions/oldIndex'
      preLoaderRoute: typeof AppTransactionsOldIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/inbox': {
      id: '/_app/transactions/inbox'
      path: '/transactions/inbox'
      fullPath: '/transactions/inbox'
      preLoaderRoute: typeof AppTransactionsInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/create': {
      id: '/_app/transactions/create'
      path: '/transactions/create'
      fullPath: '/transactions/create'
      preLoaderRoute: typeof AppTransactionsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/cashflow': {
      id: '/_app/reports/cashflow'
      path: '/reports/cashflow'
      fullPath: '/reports/cashflow'
      preLoaderRoute: typeof AppReportsCashflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/$id': {
      id: '/_app/connections/$id'
      path: '/connections/$id'
      fullPath: '/connections/$id'
      preLoaderRoute: typeof AppConnectionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/old': {
      id: '/_app/categories/old'
      path: '/categories/old'
      fullPath: '/categories/old'
      preLoaderRoute: typeof AppCategoriesOldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/new': {
      id: '/_app/categories/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof AppCategoriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/$id': {
      id: '/_app/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof AppCategoriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/create': {
      id: '/_app/budgets/create'
      path: '/budgets/create'
      fullPath: '/budgets/create'
      preLoaderRoute: typeof AppBudgetsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/$id': {
      id: '/_app/budgets/$id'
      path: '/budgets/$id'
      fullPath: '/budgets/$id'
      preLoaderRoute: typeof AppBudgetsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/new': {
      id: '/_app/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AppAccountsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$id': {
      id: '/_app/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/institutions/': {
      id: '/_app/settings/institutions/'
      path: '/settings/institutions'
      fullPath: '/settings/institutions'
      preLoaderRoute: typeof AppSettingsInstitutionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/connect/': {
      id: '/_app/connections/connect/'
      path: '/connections/connect'
      fullPath: '/connections/connect'
      preLoaderRoute: typeof AppConnectionsConnectIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/rules/': {
      id: '/_app/categories/rules/'
      path: '/categories/rules'
      fullPath: '/categories/rules'
      preLoaderRoute: typeof AppCategoriesRulesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/connect/callback': {
      id: '/_app/connections/connect/callback'
      path: '/connections/connect/callback'
      fullPath: '/connections/connect/callback'
      preLoaderRoute: typeof AppConnectionsConnectCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/rules/create': {
      id: '/_app/categories/rules/create'
      path: '/categories/rules/create'
      fullPath: '/categories/rules/create'
      preLoaderRoute: typeof AppCategoriesRulesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/$id_/edit': {
      id: '/_app/categories/$id_/edit'
      path: '/categories/$id/edit'
      fullPath: '/categories/$id/edit'
      preLoaderRoute: typeof AppCategoriesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$id_/edit': {
      id: '/_app/accounts/$id_/edit'
      path: '/accounts/$id/edit'
      fullPath: '/accounts/$id/edit'
      preLoaderRoute: typeof AppAccountsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsIdRoute: typeof AppAccountsIdRoute
  AppAccountsNewRoute: typeof AppAccountsNewRoute
  AppBudgetsIdRoute: typeof AppBudgetsIdRoute
  AppBudgetsCreateRoute: typeof AppBudgetsCreateRoute
  AppCategoriesIdRoute: typeof AppCategoriesIdRoute
  AppCategoriesNewRoute: typeof AppCategoriesNewRoute
  AppCategoriesOldRoute: typeof AppCategoriesOldRoute
  AppConnectionsIdRoute: typeof AppConnectionsIdRoute
  AppReportsCashflowRoute: typeof AppReportsCashflowRoute
  AppTransactionsCreateRoute: typeof AppTransactionsCreateRoute
  AppTransactionsInboxRoute: typeof AppTransactionsInboxRoute
  AppTransactionsOldIndexRoute: typeof AppTransactionsOldIndexRoute
  AppUserEditRoute: typeof AppUserEditRoute
  AppToolsLoanLazyRoute: typeof AppToolsLoanLazyRoute
  AppToolsMortgageLazyRoute: typeof AppToolsMortgageLazyRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppBudgetsIndexRoute: typeof AppBudgetsIndexRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppConnectionsIndexRoute: typeof AppConnectionsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppUserIndexRoute: typeof AppUserIndexRoute
  AppAccountsIdEditRoute: typeof AppAccountsIdEditRoute
  AppCategoriesIdEditRoute: typeof AppCategoriesIdEditRoute
  AppCategoriesRulesCreateRoute: typeof AppCategoriesRulesCreateRoute
  AppConnectionsConnectCallbackRoute: typeof AppConnectionsConnectCallbackRoute
  AppCategoriesRulesIndexRoute: typeof AppCategoriesRulesIndexRoute
  AppConnectionsConnectIndexRoute: typeof AppConnectionsConnectIndexRoute
  AppSettingsInstitutionsIndexRoute: typeof AppSettingsInstitutionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsIdRoute: AppAccountsIdRoute,
  AppAccountsNewRoute: AppAccountsNewRoute,
  AppBudgetsIdRoute: AppBudgetsIdRoute,
  AppBudgetsCreateRoute: AppBudgetsCreateRoute,
  AppCategoriesIdRoute: AppCategoriesIdRoute,
  AppCategoriesNewRoute: AppCategoriesNewRoute,
  AppCategoriesOldRoute: AppCategoriesOldRoute,
  AppConnectionsIdRoute: AppConnectionsIdRoute,
  AppReportsCashflowRoute: AppReportsCashflowRoute,
  AppTransactionsCreateRoute: AppTransactionsCreateRoute,
  AppTransactionsInboxRoute: AppTransactionsInboxRoute,
  AppTransactionsOldIndexRoute: AppTransactionsOldIndexRoute,
  AppUserEditRoute: AppUserEditRoute,
  AppToolsLoanLazyRoute: AppToolsLoanLazyRoute,
  AppToolsMortgageLazyRoute: AppToolsMortgageLazyRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppBudgetsIndexRoute: AppBudgetsIndexRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppConnectionsIndexRoute: AppConnectionsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppUserIndexRoute: AppUserIndexRoute,
  AppAccountsIdEditRoute: AppAccountsIdEditRoute,
  AppCategoriesIdEditRoute: AppCategoriesIdEditRoute,
  AppCategoriesRulesCreateRoute: AppCategoriesRulesCreateRoute,
  AppConnectionsConnectCallbackRoute: AppConnectionsConnectCallbackRoute,
  AppCategoriesRulesIndexRoute: AppCategoriesRulesIndexRoute,
  AppConnectionsConnectIndexRoute: AppConnectionsConnectIndexRoute,
  AppSettingsInstitutionsIndexRoute: AppSettingsInstitutionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppRoute: AppRouteWithChildren,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  UserdeletedLazyRoute: UserdeletedLazyRoute,
  LoginCallbackRoute: LoginCallbackRoute,
  LoginForgotPasswordRoute: LoginForgotPasswordRoute,
  LoginValidateotpRoute: LoginValidateotpRoute,
  OnboardingRegisterRoute: OnboardingRegisterRoute,
  OnboardingWaiting_listRoute: OnboardingWaiting_listRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
