import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import helmet from 'helmet';
import compression from 'compression';
import { Logger } from 'nestjs-pino';
import { version } from './../package.json';
import metadata from './metadata'; // file auto-generated by the "PluginMetadataGenerator"
import { INestApplication, ValidationPipe } from '@nestjs/common';
import express from 'express';

const isProduction = process.env.NODE_ENV === 'production';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    bufferLogs: true,
    // Disable bodyParser because Better-Auth.
    // Don't worry, the library will automatically re-add the default body parsers.
    // bodyParser: false,
  });
  if (isProduction) {
    app.useLogger(app.get(Logger));
  }

  // Configure EXPRESS server
  app.use(express.json({ limit: '5mb' }));
  app.use(express.urlencoded({ limit: '5mb', extended: true }));

  // Global validation pipe — strips unknown fields and rejects invalid payloads
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
    }),
  );

  // CORS
  const allowedOriginsRawValue = process.env.ALLOWED_CORS_ORIGINS ?? '';
  const allowedOrigins = allowedOriginsRawValue.split(',');

  app.enableCors({
    origin: allowedOrigins,
    methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
    credentials: true,
  });
  app.use(helmet());
  app.use(compression());

  // Configure Swagger
  const docsPath = 'docs';
  await configureSwagger(app, docsPath);

  // Start server
  console.log('Starting server...');
  const port = process.env.PORT ?? 5000;
  await app.listen(port);
  console.log(`Guallet is running on PORT: ${port}`);
  console.log(`Version:  ${version}`);
  console.log(
    `Visit:  ${await app.getUrl()}/${docsPath} to open the Swagger documentation`,
  );
}

const configureSwagger = async (app: INestApplication, docsPath: string) => {
  try {
    const openApiConfig = new DocumentBuilder()
      .setTitle('Guallet API')
      .setDescription('Personal finance manager')
      .setVersion(version)
      .addBearerAuth()
      .build();
    await SwaggerModule.loadPluginMetadata(metadata);
    const document = SwaggerModule.createDocument(app, openApiConfig);
    SwaggerModule.setup(docsPath, app, document);
  } catch (error) {
    console.error('Error setting up Swagger:', error);
  }
};

void bootstrap();
