#!/usr/bin/env node

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const API_BASE_URL = 'https://bankaccountdata.gocardless.com/api/v2';
const OUTPUT_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), 'output');

// Keep in sync with supportedCountries in apps/api/src/features/openbanking/sync.service.ts.
const SUPPORTED_COUNTRIES = [
  'AT',
  'BE',
  'BG',
  'HR',
  'CY',
  'CZ',
  'DK',
  'EE',
  'FI',
  'FR',
  'DE',
  'GR',
  'HU',
  'IS',
  'IE',
  'IT',
  'LV',
  'LI',
  'LT',
  'LU',
  'MT',
  'NL',
  'NO',
  'PL',
  'PT',
  'RO',
  'SK',
  'SI',
  'ES',
  'SE',
  'GB',
];

function promptLine(label, { secret = false } = {}) {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    throw new Error('Run this script in an interactive terminal to enter credentials.');
  }

  return new Promise((resolve, reject) => {
    const stdin = process.stdin;
    let value = '';

    process.stdout.write(label);
    stdin.setRawMode(true);
    stdin.resume();

    const finish = (error) => {
      stdin.off('data', onData);
      stdin.setRawMode(false);
      stdin.pause();
      process.stdout.write('\n');
      if (error) reject(error);
      else resolve(value.trim());
    };

    const onData = (chunk) => {
      for (const character of chunk.toString('utf8')) {
        if (character === '\u0003') {
          finish(new Error('Credential entry cancelled.'));
          return;
        }
        if (character === '\r' || character === '\n') {
          finish();
          return;
        }
        if (character === '\u0008' || character === '\u007f') {
          if (value.length > 0) {
            value = value.slice(0, -1);
            process.stdout.write('\b \b');
          }
          continue;
        }
        if (character >= ' ') {
          value += character;
          process.stdout.write(secret ? '*' : character);
        }
      }
    };

    stdin.on('data', onData);
  });
}

async function requestJson(url, options = {}) {
  const response = await fetch(url, {
    ...options,
    signal: AbortSignal.timeout(30_000),
    headers: {
      Accept: 'application/json',
      ...options.headers,
    },
  });

  if (!response.ok) {
    const detail = (await response.text()).slice(0, 500);
    throw new Error(`${response.status} ${response.statusText}: ${detail}`);
  }

  return response.json();
}

async function getAccessToken(clientId, clientSecret) {
  const token = await requestJson(`${API_BASE_URL}/token/new/`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ secret_id: clientId, secret_key: clientSecret }),
  });

  if (typeof token.access !== 'string' || token.access.length === 0) {
    throw new Error('Nordigen token response did not contain an access token.');
  }

  return token.access;
}

function sqlString(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replaceAll("'", "''")}'`;
}

function toSql(institutions, country) {
  const statements = [
    '-- Generated by scripts/nordigen-importer/import.mjs',
    `-- Country: ${country}`,
    '-- Run against the Guallet PostgreSQL database.',
    '',
  ];

  for (const institution of institutions) {
    const countries = Array.isArray(institution.countries)
      ? institution.countries.join(',')
      : country;
    statements.push(
      `INSERT INTO "institutions" ("name", "image_src", "user_id", "nordigen_id", "countries") VALUES (` +
        `${sqlString(institution.name)}, ${sqlString(institution.logo)}, NULL, ` +
        `${sqlString(institution.id)}, ${sqlString(countries)}) ` +
        `ON CONFLICT ("nordigen_id") DO UPDATE SET ` +
        `"name" = EXCLUDED."name", "image_src" = EXCLUDED."image_src", ` +
        `"countries" = EXCLUDED."countries";`,
    );
  }

  return `${statements.join('\n')}\n`;
}

function imageExtension(response, imageUrl) {
  const contentType = response.headers.get('content-type')?.split(';')[0].trim().toLowerCase();
  const contentTypeExtensions = new Map([
    ['image/avif', '.avif'],
    ['image/bmp', '.bmp'],
    ['image/gif', '.gif'],
    ['image/jpeg', '.jpg'],
    ['image/png', '.png'],
    ['image/svg+xml', '.svg'],
    ['image/vnd.microsoft.icon', '.ico'],
    ['image/webp', '.webp'],
    ['image/x-icon', '.ico'],
  ]);

  if (contentType && contentTypeExtensions.has(contentType)) {
    return contentTypeExtensions.get(contentType);
  }

  try {
    const extension = path.extname(new URL(imageUrl).pathname).toLowerCase();
    return /^\.[a-z0-9]{1,10}$/.test(extension) ? extension : '.bin';
  } catch {
    return '.bin';
  }
}

function safeFilename(value) {
  const filename = String(value).replace(/[^a-zA-Z0-9._-]/g, '_');
  return filename.length > 0 ? filename : 'institution';
}

async function downloadImage(url, destination) {
  const response = await fetch(url, { signal: AbortSignal.timeout(30_000) });
  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText}`);
  }

  const extension = imageExtension(response, url);
  const bytes = new Uint8Array(await response.arrayBuffer());
  const filename = `${safeFilename(path.basename(destination))}${extension}`;
  const imagePath = path.join(path.dirname(destination), filename);
  await writeFile(imagePath, bytes);
  return filename;
}

async function syncCountry(country, accessToken, failures) {
  const countryDir = path.join(OUTPUT_DIR, country);
  const imageDir = path.join(countryDir, 'images');
  await mkdir(imageDir, { recursive: true });

  let institutions;
  try {
    institutions = await requestJson(
      `${API_BASE_URL}/institutions/?country=${encodeURIComponent(country)}`,
      { headers: { Authorization: `Bearer ${accessToken}` } },
    );
    if (!Array.isArray(institutions)) {
      throw new Error('Institution response was not a JSON array.');
    }
  } catch (error) {
    failures.push(`${country}: institution request failed: ${error.message}`);
    console.error(`[${country}] Institution request failed: ${error.message}`);
    return;
  }

  await writeFile(
    path.join(countryDir, 'institutions.json'),
    `${JSON.stringify(institutions, null, 2)}\n`,
  );
  await writeFile(path.join(countryDir, 'institutions.sql'), toSql(institutions, country));

  let downloaded = 0;
  for (const institution of institutions) {
    if (typeof institution.logo !== 'string' || institution.logo.length === 0) continue;
    const imageBase = path.join(imageDir, safeFilename(institution.id ?? institution.name ?? 'institution'));
    try {
      await downloadImage(institution.logo, imageBase);
      downloaded += 1;
    } catch (error) {
      const message = `${country}/${institution.id ?? institution.name}: image download failed: ${error.message}`;
      failures.push(message);
      console.error(`[${country}] ${message}`);
    }
  }

  console.log(`[${country}] Saved ${institutions.length} institutions and ${downloaded} images.`);
}

async function main() {
  console.log('Nordigen institution backup');
  const clientId = await promptLine('Nordigen client ID: ');
  const clientSecret = await promptLine('Nordigen client secret: ', { secret: true });
  if (!clientId || !clientSecret) throw new Error('Client ID and secret are required.');

  console.log('Requesting Nordigen access token...');
  const accessToken = await getAccessToken(clientId, clientSecret);
  const failures = [];
  await mkdir(OUTPUT_DIR, { recursive: true });

  for (const country of SUPPORTED_COUNTRIES) {
    console.log(`[${country}] Fetching institutions...`);
    await syncCountry(country, accessToken, failures);
  }

  console.log(`Backup finished. Output: ${OUTPUT_DIR}`);
  if (failures.length > 0) {
    console.error(`Completed with ${failures.length} failure(s):`);
    for (const failure of failures) console.error(`- ${failure}`);
    process.exitCode = 1;
  }
}

main().catch((error) => {
  console.error(`Backup failed: ${error.message}`);
  process.exitCode = 1;
});
