import {
  IconActivity,
  IconAlertTriangle,
  IconArrowBackUp,
  IconArrowRight,
  IconArrowsLeftRight,
  IconBabyCarriage,
  IconBallFootball,
  IconBalloon,
  IconBarbell,
  IconBasket,
  IconBed,
  IconBike,
  IconBolt,
  IconBook,
  IconBriefcase,
  IconBuilding,
  IconBuildingBank,
  IconBuildingStore,
  IconBus,
  IconCamera,
  IconCar,
  IconCash,
  IconChartBar,
  IconClock,
  IconCoffee,
  IconConfetti,
  IconCreditCard,
  IconCup,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTv,
  IconDiamond,
  IconDice,
  IconDots,
  IconDroplet,
  IconEye,
  IconFlower,
  IconGasStation,
  IconGift,
  IconGuitarPick,
  IconHammer,
  IconHeart,
  IconHeartHandshake,
  IconHome,
  IconLego,
  IconMap,
  IconMapPin,
  IconMovie,
  IconMusic,
  IconPackage,
  IconPalette,
  IconParking,
  IconPaw,
  IconPencil,
  IconPercentage,
  IconPhone,
  IconPigMoney,
  IconPill,
  IconPlane,
  IconPlug,
  IconQuestionMark,
  IconReceipt,
  IconRun,
  IconSchool,
  IconScissors,
  IconShield,
  IconShirt,
  IconShoppingCart,
  IconSofa,
  IconSparkles,
  IconStar,
  IconStethoscope,
  IconTag,
  IconTools,
  IconToolsKitchen2,
  IconToolsKitchen3,
  IconTree,
  IconTrendingUp,
  IconTrophy,
  IconUsers,
  IconWalk,
  IconWifi,
  type Icon,
  type IconProps,
} from '@tabler/icons-react';
import {
  categoryIconFallbackName,
  categoryIconNames,
  isCategoryIconName,
} from '@guallet/theme';
import type { ComponentType, FC } from 'react';

const tablerCategoryIcons = [
  IconActivity,
  IconAlertTriangle,
  IconArrowBackUp,
  IconArrowRight,
  IconArrowsLeftRight,
  IconBabyCarriage,
  IconBallFootball,
  IconBalloon,
  IconBarbell,
  IconBasket,
  IconBed,
  IconBike,
  IconBolt,
  IconBook,
  IconBriefcase,
  IconBuilding,
  IconBuildingBank,
  IconBuildingStore,
  IconBus,
  IconCamera,
  IconCar,
  IconCash,
  IconChartBar,
  IconClock,
  IconCoffee,
  IconConfetti,
  IconCreditCard,
  IconCup,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTv,
  IconDiamond,
  IconDice,
  IconDots,
  IconDroplet,
  IconEye,
  IconFlower,
  IconGasStation,
  IconGift,
  IconGuitarPick,
  IconHammer,
  IconHeart,
  IconHeartHandshake,
  IconHome,
  IconLego,
  IconMap,
  IconMapPin,
  IconMovie,
  IconMusic,
  IconPackage,
  IconPalette,
  IconParking,
  IconPaw,
  IconPencil,
  IconPercentage,
  IconPhone,
  IconPigMoney,
  IconPill,
  IconPlane,
  IconPlug,
  IconQuestionMark,
  IconReceipt,
  IconRun,
  IconSchool,
  IconScissors,
  IconShield,
  IconShirt,
  IconShoppingCart,
  IconSofa,
  IconSparkles,
  IconStar,
  IconStethoscope,
  IconTag,
  IconTools,
  IconToolsKitchen2,
  IconToolsKitchen3,
  IconTree,
  IconTrendingUp,
  IconTrophy,
  IconUsers,
  IconWalk,
  IconWifi,
] as const satisfies readonly Icon[];

function createLunaIcon(
  IconComponent: ComponentType<IconProps>,
  displayName: string,
): FC<IconProps> {
  const LunaIcon: FC<IconProps> = (props) => (
    <IconComponent stroke={1.5} {...props} />
  );
  LunaIcon.displayName = displayName;
  return LunaIcon;
}

const lunaCategoryIcons = tablerCategoryIcons.map((IconComponent, index) =>
  createLunaIcon(
    IconComponent,
    `${categoryIconNames[index].replace(/^Icon/, '')}Icon`,
  ),
);

export const [
  ActivityIcon,
  AlertTriangleIcon,
  ArrowBackUpIcon,
  ArrowRightIcon,
  ArrowsLeftRightIcon,
  BabyCarriageIcon,
  BallFootballIcon,
  BalloonIcon,
  BarbellIcon,
  BasketIcon,
  BedIcon,
  BikeIcon,
  BoltIcon,
  BookIcon,
  BriefcaseIcon,
  BuildingIcon,
  BuildingBankIcon,
  BuildingStoreIcon,
  BusIcon,
  CameraIcon,
  CarIcon,
  CashIcon,
  ChartBarIcon,
  ClockIcon,
  CoffeeIcon,
  ConfettiIcon,
  CreditCardIcon,
  CupIcon,
  DeviceGamepad2Icon,
  DeviceLaptopIcon,
  DeviceMobileIcon,
  DeviceTvIcon,
  DiamondIcon,
  DiceIcon,
  DotsIcon,
  DropletIcon,
  EyeIcon,
  FlowerIcon,
  GasStationIcon,
  GiftIcon,
  GuitarIcon,
  HammerIcon,
  HeartIcon,
  HeartHandshakeIcon,
  HomeIcon,
  LegoIcon,
  MapIcon,
  MapPinIcon,
  MovieIcon,
  MusicIcon,
  PackageIcon,
  PaletteIcon,
  ParkingIcon,
  PawIcon,
  PencilIcon,
  PercentageIcon,
  PhoneIcon,
  PigMoneyIcon,
  PillIcon,
  PlaneIcon,
  PlugIcon,
  QuestionMarkIcon,
  ReceiptIcon,
  RunIcon,
  SchoolIcon,
  ScissorsIcon,
  ShieldIcon,
  ShirtIcon,
  ShoppingCartIcon,
  SofaIcon,
  SparklesIcon,
  StarIcon,
  StethoscopeIcon,
  TagIcon,
  ToolsIcon,
  ToolsKitchen2Icon,
  ToolsKitchen3Icon,
  TreeIcon,
  TrendingUpIcon,
  TrophyIcon,
  UsersIcon,
  WalkIcon,
  WifiIcon,
] = lunaCategoryIcons;

export const MoneyIcon = CashIcon;
export const UnknownCategoryIcon = QuestionMarkIcon;

export interface CategoryIconProps extends Omit<IconProps, 'name'> {
  name?: string | null;
}

/** Renders a supported persisted icon with a safe fallback. */
export function CategoryIcon({ name, ...props }: Readonly<CategoryIconProps>) {
  const resolvedName = isCategoryIconName(name)
    ? name
    : categoryIconFallbackName;
  const iconIndex = categoryIconNames.indexOf(resolvedName);
  const IconComponent = lunaCategoryIcons[iconIndex] ?? QuestionMarkIcon;

  return <IconComponent {...props} />;
}
