/** Stable category icon identifiers persisted by the API. */
export const categoryIconNames = [
  'IconActivity',
  'IconAlertTriangle',
  'IconArrowBackUp',
  'IconArrowRight',
  'IconArrowsLeftRight',
  'IconBabyCarriage',
  'IconBallFootball',
  'IconBalloon',
  'IconBarbell',
  'IconBasket',
  'IconBed',
  'IconBike',
  'IconBolt',
  'IconBook',
  'IconBriefcase',
  'IconBuilding',
  'IconBuildingBank',
  'IconBuildingStore',
  'IconBus',
  'IconCamera',
  'IconCar',
  'IconCash',
  'IconChartBar',
  'IconClock',
  'IconCoffee',
  'IconConfetti',
  'IconCreditCard',
  'IconCup',
  'IconDeviceGamepad2',
  'IconDeviceLaptop',
  'IconDeviceMobile',
  'IconDeviceTv',
  'IconDiamond',
  'IconDice',
  'IconDots',
  'IconDroplet',
  'IconEye',
  'IconFlower',
  'IconGasStation',
  'IconGift',
  'IconGuitar',
  'IconHammer',
  'IconHeart',
  'IconHeartHandshake',
  'IconHome',
  'IconLego',
  'IconMap',
  'IconMapPin',
  'IconMovie',
  'IconMusic',
  'IconPackage',
  'IconPalette',
  'IconParking',
  'IconPaw',
  'IconPencil',
  'IconPercentage',
  'IconPhone',
  'IconPigMoney',
  'IconPill',
  'IconPlane',
  'IconPlug',
  'IconQuestionMark',
  'IconReceipt',
  'IconRun',
  'IconSchool',
  'IconScissors',
  'IconShield',
  'IconShirt',
  'IconShoppingCart',
  'IconSofa',
  'IconSparkles',
  'IconStar',
  'IconStethoscope',
  'IconTag',
  'IconTools',
  'IconToolsKitchen2',
  'IconToolsKitchen3',
  'IconTree',
  'IconTrendingUp',
  'IconTrophy',
  'IconUsers',
  'IconWalk',
  'IconWifi',
] as const;

export type CategoryIconName = (typeof categoryIconNames)[number];

export const selectableCategoryIconNames = [
  'IconCash',
  'IconBriefcase',
  'IconHome',
  'IconBuildingBank',
  'IconPlug',
  'IconShield',
  'IconShoppingCart',
  'IconToolsKitchen3',
  'IconCup',
  'IconBasket',
  'IconCar',
  'IconMovie',
  'IconPlane',
  'IconBalloon',
  'IconBike',
  'IconShirt',
  'IconLego',
  'IconBabyCarriage',
  'IconSchool',
  'IconStethoscope',
  'IconPaw',
  'IconPigMoney',
  'IconCreditCard',
  'IconHeartHandshake',
  'IconGift',
  'IconQuestionMark',
] as const satisfies readonly CategoryIconName[];

export const categoryIconFallbackName: CategoryIconName = 'IconQuestionMark';

const categoryIconNameSet = new Set<string>(categoryIconNames);

/** Returns whether a value is a supported persisted category icon name. */
export function isCategoryIconName(value: unknown): value is CategoryIconName {
  return typeof value === 'string' && categoryIconNameSet.has(value);
}
