// Frozen schema for the initial migrations; do not regenerate when entities change.
import type { SchemaSnapshot } from './schema-validation';

export const applicationBaseline: SchemaSnapshot[] = [
  {
    name: 'nordigen_token',
    columns: [
      {
        name: 'access_expires_on',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'access',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'integer',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'increment',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'refresh_expires_on',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'refresh',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'notifications',
    columns: [
      {
        name: 'action',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'icon',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'is_read',
        type: 'boolean',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'false',
        enum: null,
        array: false,
      },
      {
        name: 'message',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'type',
        type: 'enum',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: "'info'",
        enum: ['info', 'warning', 'important', 'action_required'],
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'nordigen_requisitions',
    columns: [
      {
        name: 'account_selection',
        type: 'boolean',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'accounts',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'agreement',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'created',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'institution_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'link',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'redirect_immediate',
        type: 'boolean',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'redirect',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'reference',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'ssn',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'status',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'user_language',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'nordigen_accounts',
    columns: [
      {
        name: 'bic',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'cashAccountType',
        type: 'enum',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: "'UNKNOWN'",
        enum: [
          'CACC',
          'CARD',
          'CASH',
          'CHAR',
          'CISH',
          'COMM',
          'CPAC',
          'LLSV',
          'LOAN',
          'MGLD',
          'MOMA',
          'NREX',
          'ODFT',
          'ONDP',
          'OTHR',
          'SACC',
          'SLRY',
          'SVGS',
          'TAXE',
          'TRAN',
          'TRAS',
          'VACC',
          'NFCA',
          'UNKNOWN',
        ],
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'created',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'currency',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'details_raw',
        type: 'jsonb',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'details',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'iban',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'institution_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'last_accessed',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'last_refreshed',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'linked_account_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'maskedPan',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'metadata_raw',
        type: 'jsonb',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'metadata_status',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'owner_name',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'product',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'resource_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'status',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'saving_goals',
    columns: [
      {
        name: 'accounts',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'description',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'priority',
        type: 'integer',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'target_amount',
        type: 'integer',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'target_date',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'userId',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'users',
    columns: [
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'date_format',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'default_currency',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'email_verified',
        type: 'boolean',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'false',
        enum: null,
        array: false,
      },
      {
        name: 'email',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'preferred_currencies',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: "''",
        enum: null,
        array: false,
      },
      {
        name: 'profile_image_url',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'roles',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: "''",
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'categories',
    columns: [
      {
        name: 'colour',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'icon',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'parentId',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [
      {
        columns: ['parentId'],
        table: 'categories',
        referencedColumns: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'accounts',
    columns: [
      {
        name: 'balance',
        type: 'numeric',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'currency',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'institutionId',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'properties',
        type: 'jsonb',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'source_name',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'source',
        type: 'enum',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: "'unknown'",
        enum: ['manual', 'imported', 'synced', 'unknown'],
        array: false,
      },
      {
        name: 'type',
        type: 'enum',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: "'unknown'",
        enum: [
          'current-account',
          'credit-card',
          'savings-account',
          'investment',
          'mortgage',
          'loan',
          'pension',
          'unknown',
        ],
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [
      {
        columns: ['institutionId'],
        table: 'institutions',
        referencedColumns: ['id'],
        onDelete: 'NO ACTION',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'transactions',
    columns: [
      {
        name: 'accountId',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'amount',
        type: 'numeric',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'categoryId',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'currency',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'date',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'description',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'externalId',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: true,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'metadata',
        type: 'jsonb',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'notes',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
    ],
    indices: [
      {
        columns: ['externalId'],
        unique: false,
        where: '',
        spatial: false,
        fulltext: false,
      },
    ],
    uniques: [
      {
        columns: ['externalId'],
      },
    ],
    foreignKeys: [
      {
        columns: ['accountId'],
        table: 'accounts',
        referencedColumns: ['id'],
        onDelete: 'NO ACTION',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
      {
        columns: ['categoryId'],
        table: 'categories',
        referencedColumns: ['id'],
        onDelete: 'SET NULL',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'institutions',
    columns: [
      {
        name: 'countries',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'image_src',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'nordigen_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: true,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [
      {
        columns: ['nordigen_id'],
      },
    ],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'ai_provider_connections',
    columns: [
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'display_name',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'encrypted_token',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'provider',
        type: 'enum',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: ['openai', 'openrouter', 'vercel_ai_gateway'],
        array: false,
      },
      {
        name: 'token_hint',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'ai_agents',
    columns: [
      {
        name: 'connection_id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'custom_prompt',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'model_id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'model_name',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [
      {
        columns: ['connection_id'],
        table: 'ai_provider_connections',
        referencedColumns: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'ai_chat_sessions',
    columns: [
      {
        name: 'agent_id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'title',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [
      {
        columns: ['agent_id'],
        table: 'ai_agents',
        referencedColumns: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'ai_chat_messages',
    columns: [
      {
        name: 'content',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'role',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'session_id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [
      {
        columns: ['session_id'],
        table: 'ai_chat_sessions',
        referencedColumns: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'regular_payments',
    columns: [
      {
        name: 'amount',
        type: 'numeric',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'cadence',
        type: 'enum',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: ['weekly', 'biweekly', 'monthly', 'quarterly', 'yearly'],
        array: false,
      },
      {
        name: 'categoryId',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'currency',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'imageUrl',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'startDate',
        type: 'date',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'type',
        type: 'enum',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: ['subscription', 'regular_payment', 'regular_income'],
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [
      {
        columns: ['categoryId'],
        table: 'categories',
        referencedColumns: ['id'],
        onDelete: 'SET NULL',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'categorization_rules',
    columns: [
      {
        name: 'condition_logic',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: "'and'",
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'description',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: "''",
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'is_active',
        type: 'boolean',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'true',
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'order',
        type: 'integer',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'result_category_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'rule_conditions',
    columns: [
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'field',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'operator',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'order',
        type: 'integer',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'ruleId',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'value',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [
      {
        columns: ['ruleId'],
        table: 'categorization_rules',
        referencedColumns: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'budgets',
    columns: [
      {
        name: 'amount',
        type: 'numeric',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'colour',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'created_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'currency',
        type: 'character varying',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'deleted_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'icon',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: true,
        generationStrategy: 'uuid',
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'name',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updated_at',
        type: 'timestamp without time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'now()',
        enum: null,
        array: false,
      },
      {
        name: 'user_id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
  {
    name: 'budget_categories',
    columns: [
      {
        name: 'budget_id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'category_id',
        type: 'uuid',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [
      {
        columns: ['budget_id'],
        unique: false,
        where: '',
        spatial: false,
        fulltext: false,
      },
      {
        columns: ['category_id'],
        unique: false,
        where: '',
        spatial: false,
        fulltext: false,
      },
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: ['budget_id'],
        table: 'budgets',
        referencedColumns: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
        deferrable: null,
      },
      {
        columns: ['category_id'],
        table: 'categories',
        referencedColumns: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
        deferrable: null,
      },
    ],
    checks: [],
  },
];
