// Frozen schema for the initial migrations; do not regenerate when entities change.
import type { SchemaSnapshot } from './schema-validation';

export const authBaseline: SchemaSnapshot[] = [
  {
    name: 'auth_accounts',
    columns: [
      {
        name: 'accessToken',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'accessTokenExpiresAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'accountId',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'createdAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'CURRENT_TIMESTAMP',
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'idToken',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'password',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'providerId',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'refreshToken',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'refreshTokenExpiresAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'scope',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updatedAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'userId',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [
      {
        columns: ['userId'],
        unique: false,
        where: '',
        spatial: false,
        fulltext: false,
      },
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: ['userId'],
        table: 'users',
        referencedColumns: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'session',
    columns: [
      {
        name: 'createdAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'CURRENT_TIMESTAMP',
        enum: null,
        array: false,
      },
      {
        name: 'expiresAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'ipAddress',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'token',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: true,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updatedAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'userAgent',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: true,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'userId',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [
      {
        columns: ['userId'],
        unique: false,
        where: '',
        spatial: false,
        fulltext: false,
      },
    ],
    uniques: [
      {
        columns: ['token'],
      },
    ],
    foreignKeys: [
      {
        columns: ['userId'],
        table: 'users',
        referencedColumns: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'NO ACTION',
        deferrable: null,
      },
    ],
    checks: [],
  },
  {
    name: 'verification',
    columns: [
      {
        name: 'createdAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'CURRENT_TIMESTAMP',
        enum: null,
        array: false,
      },
      {
        name: 'expiresAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'id',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: true,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'identifier',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
      {
        name: 'updatedAt',
        type: 'timestamp with time zone',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: 'CURRENT_TIMESTAMP',
        enum: null,
        array: false,
      },
      {
        name: 'value',
        type: 'text',
        length: '',
        precision: null,
        scale: null,
        nullable: false,
        primary: false,
        unique: false,
        generated: false,
        generationStrategy: null,
        default: null,
        enum: null,
        array: false,
      },
    ],
    indices: [
      {
        columns: ['identifier'],
        unique: false,
        where: '',
        spatial: false,
        fulltext: false,
      },
    ],
    uniques: [],
    foreignKeys: [],
    checks: [],
  },
];
