name: EAS Update - Development
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm install
        working-directory: apps/mobile

      - name: Create DEV .env file
        working-directory: apps/mobile
        run: |
          touch .env
          echo {{ secrets.MOBILE_ENV_FILE_DEV }} >> .env

      - name: Publish update
        run: eas update --auto
        working-directory: apps/mobile
